import { mkdirSync, writeFileSync } from 'node:fs'
import { defineNuxtModule, addPlugin, createResolver, addImportsDir } from '@nuxt/kit'
import type { AtprotoNuxtOptions } from './types'

// Module options TypeScript interface definition
export default defineNuxtModule<AtprotoNuxtOptions>({
  meta: {
    name: 'nuxt-atproto',
    configKey: 'atproto',
  },
  defaults: {
    serviceEndpoint: {
      private: 'https://bsky.social',
      public: 'https://public.api.bsky.app',
    },
    oauth: {
      clientMetadata: {
        // load the client_metadata.json asynchronously from the URL
        remote: '',
        // or use the local client_metadata.json generated by `nuxt-atproto`
        local: {
          client_id: '',
          client_name: '',
          client_uri: '',
          logo_uri: '',
          tos_uri: '',
          policy_uri: '',
          redirect_uris: [],
          scope: 'atproto',
          grant_types: [],
          response_types: [],
          token_endpoint_auth_method: 'none',
          application_type: 'web',
          dpop_bound_access_tokens: true,
        },
      },
      signInOptions: {
        state: '',
        prompt: 'login',
        scope: 'atproto',
        ui_locales: 'en',
      },
    },
    debug: true,
  },
  setup(_options, _nuxt) {
    const { resolve } = createResolver(import.meta.url)

    const publicDir = resolve(_nuxt.options.rootDir, 'public')

    _nuxt.options.runtimeConfig.public.atproto = _options

    _nuxt.options.build.transpile = _nuxt.options.build.transpile || []
    _nuxt.options.build.transpile.push(/@atproto\//)

    _nuxt.hook('vite:extendConfig', (viteConfig) => {
      const config = viteConfig as import('vite').UserConfig

      config.optimizeDeps = {
        ...config.optimizeDeps,
        include: [
          ...(config.optimizeDeps?.include ?? []),
          '@atproto/oauth-client-browser',
          '@atproto/api',
        ],
      }

      config.build = {
        ...config.build,
        commonjsOptions: {
          ...config.build?.commonjsOptions,
          include: [
            ...(Array.isArray(config.build?.commonjsOptions?.include)
              ? config.build.commonjsOptions.include
              : []),
            /node_modules\/core-js/,
          ],
        },
      }

      config.define = {
        ...config.define,
        'process.env': config.define?.['process.env'] ?? {},
      }
    })

    addImportsDir(resolve('./runtime/app/composables'))
    addImportsDir(resolve('./runtime/app/utils'))
    addPlugin({
      src: resolve('./runtime/app/plugins/atproto.client'),
      mode: 'client',
    })

    try {
      mkdirSync(publicDir, { recursive: true })
      writeFileSync(
        `${publicDir}/client-metadata.json`,
        JSON.stringify(_options.oauth.clientMetadata.local, null, 2),
      )
    }
    catch (error: unknown) {
      console.warn('[nuxt-atproto] Failed to write public/client-metadata.json:', error)
    }
  },
})
